default_stages:
- commit
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args:
    - --in-place
    - --remove-unused-variables
    - --remove-all-unused-imports
    - --expand-star-imports
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args:
    - -l
    - '118'
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.28.0
  hooks:
  - id: commitizen
    stages:
    - commit-msg
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-toml
    args:
    - --autofix
  - id: pretty-format-yaml
    args:
    - --autofix
- repo: meta
  hooks:
  - id: check-useless-excludes

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.0
  hooks:
  - id: markdownlint-fix
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
    types_or:
    - css
    - javascript
    - json
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
    args:
    - --profile
    - black
