name: Release
on:
  push:
    branches:
    - main
    - dev
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx -y --package=@google/semantic-release-replace-plugin --package=semantic-release semantic-release
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
